// import './globals.css'
// import { Inter } from 'next/font/google'
// // import { GetServerSidePropsContext, NextApiRequest, NextApiResponse } from "next";
// // import { NextAuthOptions } from "next-auth";
// // import { getServerSession } from "next-auth";

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children}) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
